name: myenvironment
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - streamlit==1.47.1
      - tensorflow==2.19.0
      - pandas==2.3.1
      - pillow==11.3.0
      - matplotlib==3.10.5
      - scikit-learn==1.5.0
      - seaborn==0.13.2